GET http://localhost:3000/api/members

###
POST http://localhost:3000/api/members
Content-Type: application/json

{
  "name":"Hun",
  "team":"engineering",
  "position":"Frontend Developer",
  "emailAddress":"gunn.kim@google.com",
  "phoneNumber":"010-xxxx-xxxx",
  "admissionDate":"2022/02/10",
  "birthday":"1992/01/09",
  "profileImage":"profile1.png"
}

###
PUT http://localhost:3000/api/members/1
Content-Type: application/json

{"name": "David"}

###
DELETE http://localhost:3000/api/members/10